nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.0.1.cjs
npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.fontawesome.com/'
    npmAuthToken: '5A06BA3D-BC8B-408B-8216-21B6396427C4'
